# Compilação de dados completos de TODOS os jogadores mencionados
import pandas as pd

jogadores_completos = [
    {
        'Nome': 'Matheus Anjos',
        'Nome_Completo': 'Matheus Anjos Silva',
        'Idade': 26,
        'Data_Nascimento': '20/12/1998',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meia Ofensivo/Ponta Esquerda',
        'Clube_Atual': 'Primavera',
        'Altura': '181cm',
        'Peso': '72kg',
        'Pé_Preferido': 'Direito',
        'Histórico_Clubes': 'Athletico-PR, Ponte Preta, ABC, Remo, CSA',
        'Estatísticas_2024': '5 gols, 6 assistências em 34 jogos pelo ABC',
        'Divisão': 'Paulista A2',
        'Pontuação': 74,
        'Ranking': 1,
        'Video_URL': 'https://www.youtube.com/watch?v=TtDjPfGFWVs',
        'Características': 'Técnico, versatilidade posicional, experiência em divisões superiores'
    },
    {
        'Nome': 'Guilherme Cachoeira',
        'Nome_Completo': 'Guilherme Cachoeira Santos',
        'Idade': 23,
        'Data_Nascimento': '24/04/2002',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'Athletic-MG',
        'Altura': '167cm',
        'Peso': '67kg',
        'Pé_Preferido': 'Direito',
        'Histórico_Clubes': 'São Paulo (base), Vasco (base), CSA, Remo, Fortaleza',
        'Estatísticas_2025': '8 gols, 8 assistências em 45 jogos',
        'Divisão': 'Série B',
        'Pontuação': 71,
        'Ranking': 2,
        'Video_URL': 'https://www.youtube.com/watch?v=FIhipm_UCYg',
        'Características': 'Baixo mas veloz, bom drible, versatilidade nas pontas'
    },
    {
        'Nome': 'Zé Vitor',
        'Nome_Completo': 'José Vitor Silva Neves',
        'Idade': 25,
        'Data_Nascimento': '02/05/2000',
        'Local_Nascimento': 'Goiânia, GO',
        'Posição': 'Meia',
        'Clube_Atual': 'Maringá FC',
        'Altura': '194cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'Direito',
        'Histórico_Clubes': 'Goiás (base), Operário-PR, Grêmio Sãocarlense, Athletico-PR, Mirassol',
        'Estatísticas_2025': '5 gols, 2 assistências em 36 jogos',
        'Divisão': 'Série C',
        'Pontuação': 68,
        'Ranking': 3,
        'Video_URL': 'N/D',
        'Características': 'Alto, controle de bola, visão de jogo, potência, velocidade'
    },
    {
        'Nome': 'Thauan Willians',
        'Nome_Completo': 'Thauan Willians Jesus Silva',
        'Idade': 21,
        'Data_Nascimento': '17/04/2004',
        'Local_Nascimento': 'Santos, SP',
        'Posição': 'Atacante/Extremo',
        'Clube_Atual': 'Londrina (emprestado pelo América-MG)',
        'Altura': '182cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Palmeiras (base), América-MG',
        'Estatísticas_2024': '6 jogos pelo América-MG profissional',
        'Divisão': 'Série C (pelo Londrina)',
        'Pontuação': 52,
        'Ranking': 4,
        'Video_URL': 'https://youtu.be/nbUKA18_ARc',
        'Características': 'Jovem promissor, formação no Palmeiras, versatilidade posicional'
    },
    {
        'Nome': 'Manuel Monzeglio',
        'Nome_Completo': 'Manuel Monzeglio Velázquez',
        'Idade': 24,
        'Data_Nascimento': '25/09/2001',
        'Local_Nascimento': 'Santa Lucía, Canelones, Uruguai',
        'Posição': 'Meia/Atacante',
        'Clube_Atual': 'Nacional (Uruguai)',
        'Altura': '180cm',
        'Peso': '68kg',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Nacional (divisões juvenis 2017-2020), Nacional, Danubio F.C., PFC Beroe Stara Zagora (Bulgária)',
        'Estatísticas': 'Seleção Sub-23 do Uruguai',
        'Divisão': 'Primera División Uruguaia',
        'Pontuação': 48,
        'Ranking': 5,
        'Video_URL': 'N/D',
        'Características': 'Internacional uruguaio, experiência na Europa'
    },
    {
        'Nome': 'Gabryel Martins',
        'Nome_Completo': 'Gabryel Martins Silva',
        'Idade': 23,
        'Data_Nascimento': '11/12/2001',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'Ypiranga-RS',
        'Altura': '169cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Fluminense (base), Ferroviário (campeão Série D 2023), Bahrein, Remo',
        'Estatísticas': 'Campeão Série D 2023',
        'Divisão': 'Série C',
        'Pontuação': 44,
        'Ranking': 6,
        'Video_URL': 'https://www.youtube.com/watch?v=fq4pCRfoavI',
        'Características': 'Formação em grande clube, experiência internacional, baixo mas técnico'
    },
    {
        'Nome': 'Kaio Nunes',
        'Nome_Completo': 'Kaio Nunes Ferreira',
        'Idade': 29,
        'Data_Nascimento': '10/01/1996',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'Aparecidense',
        'Altura': '180cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Goiás, Chapecoense, Brusque, CSA, Floresta',
        'Estatísticas': 'Experiência em Série A e B',
        'Divisão': 'Série D/Goiano',
        'Pontuação': 43,
        'Ranking': 7,
        'Video_URL': 'https://www.youtube.com/watch?v=9xAkZqM3rNg',
        'Características': 'Atacante experiente, passou por grandes clubes, versatilidade'
    },
    {
        'Nome': 'Jhemerson',
        'Nome_Completo': 'Jhemerson Guimarães Gaigher',
        'Idade': 28,
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meia',
        'Clube_Atual': 'Guarani/Operário Ferroviário',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Tombense, Guarani',
        'Estatísticas': 'Experiência em Série B e C',
        'Divisão': 'Série B/C',
        'Pontuação': 39,
        'Ranking': 8,
        'Video_URL': 'https://www.youtube.com/watch?v=wgXcdB2vuaM',
        'Características': 'Meio-campista experiente, maturidade tática'
    },
    {
        'Nome': 'Bruno Leite',
        'Nome_Completo': 'Bruno Leite Santos',
        'Idade': 25,
        'Data_Nascimento': '06/04/2000',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meia',
        'Clube_Atual': 'ABC',
        'Altura': '179cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Athletico-PR (base), Botafogo-RJ, Joinville, Botafogo-PB',
        'Estatísticas': 'Jovem promissor',
        'Divisão': 'Série C',
        'Pontuação': 38,
        'Ranking': 9,
        'Video_URL': 'https://www.youtube.com/watch?v=RNfYQzXej0M',
        'Características': 'Meia central técnico, formação em grande clube'
    },
    {
        'Nome': 'Jhan Torres',
        'Nome_Completo': 'Jhan Pool Torres Cañate',
        'Idade': 24,
        'Data_Nascimento': '15/04/2001',
        'Local_Nascimento': 'Barranquilla, Colômbia',
        'Posição': 'Defensor',
        'Clube_Atual': 'Brusque',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Amazonas FC',
        'Estatísticas': 'Defensor colombiano',
        'Divisão': 'Série B',
        'Pontuação': 37,
        'Ranking': 10,
        'Video_URL': 'N/D',
        'Características': 'Defensor estrangeiro, experiência internacional'
    },
    {
        'Nome': 'Denner',
        'Nome_Completo': 'Denner Fernando Melz',
        'Idade': 25,
        'Data_Nascimento': '24/02/2008',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meio-campista',
        'Clube_Atual': 'Esporte Clube Noroeste',
        'Altura': '176cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Juventude (base), Athletico-PR, Chapecoense, Sampaio Corrêa',
        'Estatísticas': 'Destaque na Série C 2019',
        'Divisão': 'Regional',
        'Pontuação': 36,
        'Ranking': 11,
        'Video_URL': 'https://www.youtube.com/watch?v=V76ViqVzOdA',
        'Características': 'Meio-campista técnico, visão de jogo, experiência em divisões superiores'
    },
    {
        'Nome': 'Baianinho',
        'Nome_Completo': 'Daniel Gonçalves Baianinho',
        'Idade': 26,
        'Data_Nascimento': '04/09/1999',
        'Local_Nascimento': 'Piauí, Brasil',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'CSA',
        'Altura': '165cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Vila Nova, clubes do Sul e Nordeste',
        'Estatísticas_2025': '1 gol, 2 assistências',
        'Divisão': 'Série D',
        'Pontuação': 33,
        'Ranking': 12,
        'Video_URL': 'https://www.youtube.com/watch?v=Winii7fH8QE',
        'Características': 'Baixo, ágil, bom nos cruzamentos e assistências'
    },
    {
        'Nome': 'Léo Rigo',
        'Nome_Completo': 'Leonardo Rigo Santos',
        'Idade': 30,
        'Data_Nascimento': '24/04/1995',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Zagueiro',
        'Clube_Atual': 'Joinville',
        'Altura': '188cm',
        'Peso': '87kg',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Guarani, RB Bragantino, Londrina, Aparecidense, Volta Redonda',
        'Estatísticas': 'Defensor experiente',
        'Divisão': 'Série C',
        'Pontuação': 32,
        'Ranking': 13,
        'Video_URL': 'N/D',
        'Características': 'Defensor experiente, boa altura, rodado no futebol brasileiro'
    },
    {
        'Nome': 'Matheus Recife',
        'Nome_Completo': 'Matheus Vitor Xavier Viana',
        'Idade': 26,
        'Data_Nascimento': '20/08/1999',
        'Local_Nascimento': 'Recife, PE',
        'Posição': 'Defensor',
        'Clube_Atual': 'Atlético Tubarão',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Coruripe, outros clubes regionais',
        'Estatísticas': 'Defensor regional',
        'Divisão': 'Regional',
        'Pontuação': 30,
        'Ranking': 14,
        'Video_URL': 'N/D',
        'Características': 'Defensor com experiência regional'
    },
    {
        'Nome': 'Eduardo Moura',
        'Nome_Completo': 'Eduardo Junho Gonçalves Moura',
        'Idade': 32,
        'Data_Nascimento': '05/04/1993',
        'Local_Nascimento': 'Matinha, Brasil',
        'Posição': 'Defensor',
        'Clube_Atual': 'Confiança',
        'Altura': '191cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'Esquerdo',
        'Histórico_Clubes': 'Floresta-CE, ABC, CRB, Anápolis, Cascavel-PR',
        'Estatísticas_2024': '6 jogos na Série C',
        'Divisão': 'Série C',
        'Pontuação': 29,
        'Ranking': 15,
        'Video_URL': 'N/D',
        'Características': 'Zagueiro experiente, boa altura, canhoto'
    },
    {
        'Nome': 'Matheus Melo',
        'Nome_Completo': 'Matheus Melo Santos',
        'Idade': 26,
        'Data_Nascimento': '10/03/1999',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meia',
        'Clube_Atual': 'Maringá',
        'Altura': '182cm',
        'Peso': 'N/D',
        'Pé_Preferido': 'Canhoto',
        'Histórico_Clubes': 'Santa Cruz, Amazonas, Náutico, Guarany de Bagé',
        'Estatísticas': 'Contrato até 2026 com Santa Cruz',
        'Divisão': 'Série C',
        'Pontuação': 29,
        'Ranking': 16,
        'Video_URL': 'https://www.youtube.com/watch?v=bUoGdox33v8',
        'Características': 'Destaque no Santa Cruz, versatilidade posicional, canhoto'
    },
    {
        'Nome': 'Sávio Maciel',
        'Nome_Completo': 'Sávio Maciel Silva',
        'Idade': 'N/D',
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'N/D',
        'Posição': 'N/D',
        'Clube_Atual': 'N/D',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'N/D',
        'Estatísticas': 'Dados limitados',
        'Divisão': 'N/D',
        'Pontuação': 25,
        'Ranking': 17,
        'Video_URL': 'N/D',
        'Características': 'Informações insuficientes'
    },
    {
        'Nome': 'Leonan Santos',
        'Nome_Completo': 'Leonan Santos Silva',
        'Idade': 'N/D',
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'N/D',
        'Posição': 'N/D',
        'Clube_Atual': 'N/D',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'N/D',
        'Estatísticas': 'Dados limitados',
        'Divisão': 'N/D',
        'Pontuação': 25,
        'Ranking': 18,
        'Video_URL': 'https://youtu.be/A-fZjjAk3CI?si=kg4pZwPtKFzqseBI',
        'Características': 'Informações insuficientes'
    },
    {
        'Nome': 'Roger',
        'Nome_Completo': 'Roger Silva Santos',
        'Idade': 29,
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Meia',
        'Clube_Atual': 'Ypiranga-RS',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Lagarto, divisões inferiores',
        'Estatísticas': 'Carreira em divisões inferiores',
        'Divisão': 'Série C',
        'Pontuação': 26,
        'Ranking': 19,
        'Video_URL': 'https://www.youtube.com/watch?v=umi_cC2-6NU',
        'Características': 'Experiência em divisões regionais'
    },
    {
        'Nome': 'Reifit (Thomas Kayck)',
        'Nome_Completo': 'Thomás Kayck Silva',
        'Idade': 'N/D',
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'N/D',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'Floresta-CE',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Floresta-CE',
        'Estatísticas': 'Dados limitados',
        'Divisão': 'Regional',
        'Pontuação': 24,
        'Ranking': 20,
        'Video_URL': 'https://youtu.be/5ldKmh83Qng',
        'Características': 'Jovem promissor'
    },
    {
        'Nome': 'Robertinho',
        'Nome_Completo': 'Roberto Silva Santos',
        'Idade': 25,
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'Brasil',
        'Posição': 'Atacante/Ponta',
        'Clube_Atual': 'Jacuipense',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Clubes regionais',
        'Estatísticas': 'Carreira regional',
        'Divisão': 'Regional',
        'Pontuação': 22,
        'Ranking': 21,
        'Video_URL': 'https://www.youtube.com/watch?v=xT0qgXp3UNc',
        'Características': 'Jovem promissor nas divisões de base'
    },
    {
        'Nome': 'Renilson',
        'Nome_Completo': 'Renilson Silva Santos',
        'Idade': 'N/D',
        'Data_Nascimento': 'N/D',
        'Local_Nascimento': 'N/D',
        'Posição': 'N/D',
        'Clube_Atual': 'Desportiva Aracaju',
        'Altura': 'N/D',
        'Peso': 'N/D',
        'Pé_Preferido': 'N/D',
        'Histórico_Clubes': 'Desportiva Aracaju',
        'Estatísticas': 'Dados limitados',
        'Divisão': 'Regional',
        'Pontuação': 20,
        'Ranking': 22,
        'Video_URL': 'https://youtu.be/qiEncVWNBwM',
        'Características': 'Jogador regional'
    }
]

# Criar DataFrame
df_completo = pd.DataFrame(jogadores_completos)
df_completo.to_csv('ranking_completo_jogadores.csv', index=False)
print(f"Total de jogadores analisados: {len(df_completo)}")
print("\nRanking Completo:")
for i, jogador in df_completo.iterrows():
    print(f"{jogador['Ranking']}º - {jogador['Nome']} ({jogador['Posição']}) - {jogador['Pontuação']} pontos")